Repository GSG-CF04/COVIDtracker, pull requests merged in 2021-12, with the labels that each got.

#37 Adding style and html content for statistics page
  statistics/statistics.css
  statistics/statistics.html
Labels: Waiting-review

#39 ceating page1 html file
  page1.html
Labels: Waiting-review

#43 Add current user country relates to ip location in statistics
  statistics/statistics.css
  statistics/statistics.html
  statistics/statistics.js
Labels: Waiting-review

#46 Update readme file
  README.md
Labels: Done

#45 Add responsive and dark mood code in statistics page
  images/moon.png
  statistics/statistics.css
  statistics/statistics.html
  statistics/statistics.js
Labels: Approved
